### ISSUE TITLE
View schedule (full time / part time)

### ISSUE THREAD

**Issue by ChrisKheng** [team-mariners/hungrydb#126] opened 2020-04-04 09:44 UTC
Full time -> monthly
Part time -> weekly

Including past work schedule
(Need to follow the specification)

*  In the FDS application, a week is defined to be a duration consisting of seven consecutive days, and a month is defined to be a duration consisting of four consecutive weeks.

**Comment by dcshzj** [comment] 2020-04-04 10:39
Possible duplicate of #75

**Closed** 2020-04-07 13:58 UTC
